# Generated by Django 5.2.5 on 2025-08-29 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fofoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(choices=[('chocante', 'Chocante'), ('descontraida', 'Descontraída'), ('denuncia', 'Denúncia'), ('ajuda', 'Ajuda'), ('novidade', 'Novidade')], default='descontraida', max_length=20)),
                ('reacao_feliz', models.IntegerField(default=0)),
                ('reacao_triste', models.IntegerField(default=0)),
                ('reacao_bravo', models.IntegerField(default=0)),
                ('reacao_surpreso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpo', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('fofoca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='fofocas.fofoca')),
            ],
        ),
    ]
