# Generated by Django 5.2.5 on 2025-08-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fofocas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fofocas.comentario'),
        ),
    ]
